### ISSUE TITLE
Incorrect driver response

### ISSUE THREAD

**Issue by tkurnosova** [2gis/Winium.StoreApps#100]
Драйвер возвращает ответ на любой запрос кроме создания сессии с null значением поля SessionId. Из-за чего биндинги не могут его распарсить. 
Ниже приведены списки команд и ответы от ChromeDriver
- CreateSession
{(45c49ade8e122a00a6d00e3a3dd8e098 Success: System.Collections.Generic.Dictionary`2[System.String,System.Object])}
- GoUrl
{(45c49ade8e122a00a6d00e3a3dd8e098 Success: )}
- FindElement
{(45c49ade8e122a00a6d00e3a3dd8e098 Success: System.Collections.Generic.Dictionary`2[System.String,System.Object])
То есть на каждый запрос ChromeDriver возвращает значение идентификатора сессии. Возможно это верно ещё и потому, что есть возможность работы с несколькими сессиями.

Т.о. нужно добавить значение SessionId в ответ на любой запрос к драйверу

**Comment by NickAb** [comment]
Essence of the problem
> *Driver* returns session id only for commands executed by *Driver* (e.g. NewSession, GetOrientation), not inner server (e.g. `FindElement`, `IsElementEnabled`) due to the fact that *InnerServer* has no concept of a session in it and *Driver* simply proxies responses from `InnerServer` for such commands.

This problem appeared when trying to use custom WebDriver service in .NET. Selenium bindings for .NET does not seem to expect `sessionId` in all responses.
Need to check bindings, it seems that sessionId is saved on NewSession and can be omitted in other commands if sessionId key is not present. But it would be better to support correct responses.
1. We can pass sessionId to InnerServer and make it return it in responses
2. We can parse response from InnerServer on the Driver and add sessionId here, without modifying InnerServer
3. Rework InnerServer to use simply JSON PRC so that InnerServer does not have any logic on how to handle responses for Selenium clients, so that this logic is contained in Driver only.

**Comment by NickAb** [comment]
Fixed in #103
