### ISSUE TITLE
isEnabled property doesn't work

### ISSUE THREAD

**Issue by IAPOLINARIO** [2gis/Winium.StoreApps#96]
When I try to access the Enabled property of a component, an exception is thrown. Should I perform some configuration or extra implementation for this to work?

**Comment by NickAb** [comment]
`isElementEnabled` is not implemented yet, but you can use (in python)
```py
element.get_attribute("IsEnabled")
```
Note that `element.get_attribute("IsEnabled")` will return a string containing`"true"` or `"false"`, bot a Boolean.

I have opened #97 and will fix it in nearest release, so that `element.is_enabled()` can be used instead of `element.get_attribute("IsEnabled") == "true"`.

**Comment by NickAb** [comment]
Implementation is in master, so you can try using InnerServer form sources, instead of NuGet package. Or simple use workaround if it blocks you until we make a new release, which should be soon enough.

**Comment by IAPOLINARIO** [comment]
Works perfectly ! 

Tks
